### ISSUE TITLE
I ran according to your instructions, but it reported an error

### ISSUE THREAD

**Issue by AliDva** [darkwhite220/WendlyTradingBot#2]
Traceback (most recent call last):
  File "c:\Users\Lenovo\Desktop\Wendly Trading Bot\WendlyTradingBot-main\main.py", line 10, in <module>
    class WendlyGui(Tk):
  File "c:\Users\Lenovo\Desktop\Wendly Trading Bot\WendlyTradingBot-main\main.py", line 61, in WendlyGui
    def display_menu_trading(self):
TypeError: 'staticmethod' object is not callable

**Comment by darkwhite220** [comment]
What python version you are using? 
Please try version 3.10
